//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicosWs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestasWS", Namespace="http://schemas.datacontract.org/2004/07/husiWSGeneral.Modelos")]
    public partial class RespuestasWS : object
    {
        
        private string CodigoRptaField;
        
        private string MensajeRptaField;
        
        private string resultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRpta
        {
            get
            {
                return this.CodigoRptaField;
            }
            set
            {
                this.CodigoRptaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRpta
        {
            get
            {
                return this.MensajeRptaField;
            }
            set
            {
                this.MensajeRptaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MedicosWs.ImedicosWS")]
    public interface ImedicosWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImedicosWS/idUsuarioPersonal", ReplyAction="http://tempuri.org/ImedicosWS/idUsuarioPersonalResponse")]
        System.Threading.Tasks.Task<MedicosWs.RespuestasWS> idUsuarioPersonalAsync(string idPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImedicosWS/idPersonalUsuario", ReplyAction="http://tempuri.org/ImedicosWS/idPersonalUsuarioResponse")]
        System.Threading.Tasks.Task<MedicosWs.RespuestasWS> idPersonalUsuarioAsync(string idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ImedicosWSChannel : MedicosWs.ImedicosWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ImedicosWSClient : System.ServiceModel.ClientBase<MedicosWs.ImedicosWS>, MedicosWs.ImedicosWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ImedicosWSClient() : 
                base(ImedicosWSClient.GetDefaultBinding(), ImedicosWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ImedicosWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImedicosWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ImedicosWSClient.GetBindingForEndpoint(endpointConfiguration), ImedicosWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImedicosWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ImedicosWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImedicosWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ImedicosWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImedicosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MedicosWs.RespuestasWS> idUsuarioPersonalAsync(string idPersonal)
        {
            return base.Channel.idUsuarioPersonalAsync(idPersonal);
        }
        
        public System.Threading.Tasks.Task<MedicosWs.RespuestasWS> idPersonalUsuarioAsync(string idUsuario)
        {
            return base.Channel.idPersonalUsuarioAsync(idUsuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ImedicosWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ImedicosWS))
            {
                return new System.ServiceModel.EndpointAddress("http://winpvtiws04:2710/Servicios/medicosWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ImedicosWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ImedicosWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ImedicosWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ImedicosWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ImedicosWS,
        }
    }
}
