//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datosPaciente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
    public partial class husiExceptions : object
    {
        
        private string CodigoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="husiCliente", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
    public partial class husiCliente : object
    {
        
        private string ApeClienteField;
        
        private string Cod_DipoNacField;
        
        private string Cod_dipoClienteField;
        
        private string Cod_usuarioField;
        
        private string CorreoEField;
        
        private System.DateTime CreateDateField;
        
        private string DirCasaField;
        
        private string DirOficinaField;
        
        private string EpsAsegField;
        
        private System.DateTime FecNacimientoField;
        
        private int IdAfiliaciontipoField;
        
        private int IdClienteField;
        
        private int IdClienteMadreField;
        
        private byte IdEstadoCivilField;
        
        private byte IdFactorRhField;
        
        private byte IdGrupSangreField;
        
        private int IdLugarClienteField;
        
        private int IdLugarDocuField;
        
        private int IdLugarNacField;
        
        private byte IdNivelField;
        
        private byte IdOcupacionField;
        
        private int IdReligionField;
        
        private byte IdSexoField;
        
        private byte IdTipoDocField;
        
        private byte IdZonaField;
        
        private bool IndHabilitadoField;
        
        private bool IndMuertoField;
        
        private string NomClienteField;
        
        private string NomMadreField;
        
        private string NomPadreField;
        
        private string NroHistoriaField;
        
        private string NumDocumentoField;
        
        private string ObservacionesField;
        
        private string PcteEspField;
        
        private string TelCasaField;
        
        private string TelCelularField;
        
        private string TelOficinaField;
        
        private double ValSaldoField;
        
        private string autoEnvMsjCelField;
        
        private string autoEnvMsjEmailField;
        
        private int idterceroField;
        
        private bool indAuditoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeCliente
        {
            get
            {
                return this.ApeClienteField;
            }
            set
            {
                this.ApeClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_DipoNac
        {
            get
            {
                return this.Cod_DipoNacField;
            }
            set
            {
                this.Cod_DipoNacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_dipoCliente
        {
            get
            {
                return this.Cod_dipoClienteField;
            }
            set
            {
                this.Cod_dipoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_usuario
        {
            get
            {
                return this.Cod_usuarioField;
            }
            set
            {
                this.Cod_usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoE
        {
            get
            {
                return this.CorreoEField;
            }
            set
            {
                this.CorreoEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirCasa
        {
            get
            {
                return this.DirCasaField;
            }
            set
            {
                this.DirCasaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirOficina
        {
            get
            {
                return this.DirOficinaField;
            }
            set
            {
                this.DirOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpsAseg
        {
            get
            {
                return this.EpsAsegField;
            }
            set
            {
                this.EpsAsegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNacimiento
        {
            get
            {
                return this.FecNacimientoField;
            }
            set
            {
                this.FecNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAfiliaciontipo
        {
            get
            {
                return this.IdAfiliaciontipoField;
            }
            set
            {
                this.IdAfiliaciontipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClienteMadre
        {
            get
            {
                return this.IdClienteMadreField;
            }
            set
            {
                this.IdClienteMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdEstadoCivil
        {
            get
            {
                return this.IdEstadoCivilField;
            }
            set
            {
                this.IdEstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdFactorRh
        {
            get
            {
                return this.IdFactorRhField;
            }
            set
            {
                this.IdFactorRhField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdGrupSangre
        {
            get
            {
                return this.IdGrupSangreField;
            }
            set
            {
                this.IdGrupSangreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLugarCliente
        {
            get
            {
                return this.IdLugarClienteField;
            }
            set
            {
                this.IdLugarClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLugarDocu
        {
            get
            {
                return this.IdLugarDocuField;
            }
            set
            {
                this.IdLugarDocuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLugarNac
        {
            get
            {
                return this.IdLugarNacField;
            }
            set
            {
                this.IdLugarNacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdNivel
        {
            get
            {
                return this.IdNivelField;
            }
            set
            {
                this.IdNivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdOcupacion
        {
            get
            {
                return this.IdOcupacionField;
            }
            set
            {
                this.IdOcupacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReligion
        {
            get
            {
                return this.IdReligionField;
            }
            set
            {
                this.IdReligionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdSexo
        {
            get
            {
                return this.IdSexoField;
            }
            set
            {
                this.IdSexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdTipoDoc
        {
            get
            {
                return this.IdTipoDocField;
            }
            set
            {
                this.IdTipoDocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdZona
        {
            get
            {
                return this.IdZonaField;
            }
            set
            {
                this.IdZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IndHabilitado
        {
            get
            {
                return this.IndHabilitadoField;
            }
            set
            {
                this.IndHabilitadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IndMuerto
        {
            get
            {
                return this.IndMuertoField;
            }
            set
            {
                this.IndMuertoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCliente
        {
            get
            {
                return this.NomClienteField;
            }
            set
            {
                this.NomClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMadre
        {
            get
            {
                return this.NomMadreField;
            }
            set
            {
                this.NomMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPadre
        {
            get
            {
                return this.NomPadreField;
            }
            set
            {
                this.NomPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroHistoria
        {
            get
            {
                return this.NroHistoriaField;
            }
            set
            {
                this.NroHistoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento
        {
            get
            {
                return this.NumDocumentoField;
            }
            set
            {
                this.NumDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PcteEsp
        {
            get
            {
                return this.PcteEspField;
            }
            set
            {
                this.PcteEspField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelCasa
        {
            get
            {
                return this.TelCasaField;
            }
            set
            {
                this.TelCasaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelCelular
        {
            get
            {
                return this.TelCelularField;
            }
            set
            {
                this.TelCelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelOficina
        {
            get
            {
                return this.TelOficinaField;
            }
            set
            {
                this.TelOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValSaldo
        {
            get
            {
                return this.ValSaldoField;
            }
            set
            {
                this.ValSaldoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string autoEnvMsjCel
        {
            get
            {
                return this.autoEnvMsjCelField;
            }
            set
            {
                this.autoEnvMsjCelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string autoEnvMsjEmail
        {
            get
            {
                return this.autoEnvMsjEmailField;
            }
            set
            {
                this.autoEnvMsjEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idtercero
        {
            get
            {
                return this.idterceroField;
            }
            set
            {
                this.idterceroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indAuditoria
        {
            get
            {
                return this.indAuditoriaField;
            }
            set
            {
                this.indAuditoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="habeasData", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
    public partial class habeasData : object
    {
        
        private int IdPacienteField;
        
        private string correoField;
        
        private int diasUltimaActField;
        
        private bool estCelularField;
        
        private bool estmailField;
        
        private System.DateTime fechaAct_hbCelField;
        
        private System.DateTime fechaAct_hbMailField;
        
        private string nroCelularField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPaciente
        {
            get
            {
                return this.IdPacienteField;
            }
            set
            {
                this.IdPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int diasUltimaAct
        {
            get
            {
                return this.diasUltimaActField;
            }
            set
            {
                this.diasUltimaActField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estCelular
        {
            get
            {
                return this.estCelularField;
            }
            set
            {
                this.estCelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estmail
        {
            get
            {
                return this.estmailField;
            }
            set
            {
                this.estmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaAct_hbCel
        {
            get
            {
                return this.fechaAct_hbCelField;
            }
            set
            {
                this.fechaAct_hbCelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaAct_hbMail
        {
            get
            {
                return this.fechaAct_hbMailField;
            }
            set
            {
                this.fechaAct_hbMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroCelular
        {
            get
            {
                return this.nroCelularField;
            }
            set
            {
                this.nroCelularField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="datosPaciente.IhusiClienteWS")]
    public interface IhusiClienteWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Consulta", ReplyAction="http://tempuri.org/IhusiClienteWS/ConsultaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/ConsultahusiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<string> ConsultaAsync(string nroDoc, byte tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Actualizar", ReplyAction="http://tempuri.org/IhusiClienteWS/ActualizarResponse")]
        System.Threading.Tasks.Task<string> ActualizarAsync(string Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Insertar", ReplyAction="http://tempuri.org/IhusiClienteWS/InsertarResponse")]
        System.Threading.Tasks.Task<string> InsertarAsync(string Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/ConsultaExt", ReplyAction="http://tempuri.org/IhusiClienteWS/ConsultaExtResponse")]
        System.Threading.Tasks.Task<string> ConsultaExtAsync(string paciente, byte tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/ConsultaPctesExt", ReplyAction="http://tempuri.org/IhusiClienteWS/ConsultaPctesExtResponse")]
        System.Threading.Tasks.Task<string> ConsultaPctesExtAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Pacientes", ReplyAction="http://tempuri.org/IhusiClienteWS/PacientesResponse")]
        System.Threading.Tasks.Task<string> PacientesAsync(string nroDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/consPaciente", ReplyAction="http://tempuri.org/IhusiClienteWS/consPacienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/consPacientehusiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<datosPaciente.husiCliente> consPacienteAsync(string nroDoc, byte tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Actualizar_V2", ReplyAction="http://tempuri.org/IhusiClienteWS/Actualizar_V2Response")]
        System.Threading.Tasks.Task<string> Actualizar_V2Async(datosPaciente.husiCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Actualizar_V3", ReplyAction="http://tempuri.org/IhusiClienteWS/Actualizar_V3Response")]
        System.Threading.Tasks.Task<string> Actualizar_V3Async(datosPaciente.husiCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Insertar_V2", ReplyAction="http://tempuri.org/IhusiClienteWS/Insertar_V2Response")]
        System.Threading.Tasks.Task<string> Insertar_V2Async(datosPaciente.husiCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Insertar_V3", ReplyAction="http://tempuri.org/IhusiClienteWS/Insertar_V3Response")]
        System.Threading.Tasks.Task<string> Insertar_V3Async(datosPaciente.husiCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Consulta_V2", ReplyAction="http://tempuri.org/IhusiClienteWS/Consulta_V2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/Consulta_V2husiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<datosPaciente.husiCliente> Consulta_V2Async(string nroDoc, byte tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/segmentoPaciente", ReplyAction="http://tempuri.org/IhusiClienteWS/segmentoPacienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/segmentoPacientehusiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<short> segmentoPacienteAsync(int idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/HBConsPaciente", ReplyAction="http://tempuri.org/IhusiClienteWS/HBConsPacienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/HBConsPacientehusiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<datosPaciente.habeasData> HBConsPacienteAsync(string nroDoc, short tipoDoc, System.DateTime fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhusiClienteWS/Consulta_V3", ReplyAction="http://tempuri.org/IhusiClienteWS/Consulta_V3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(datosPaciente.husiExceptions), Action="http://tempuri.org/IhusiClienteWS/Consulta_V3husiExceptionsFault", Name="husiExceptions", Namespace="http://schemas.datacontract.org/2004/07/CitasWS")]
        System.Threading.Tasks.Task<datosPaciente.husiCliente> Consulta_V3Async(string idCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IhusiClienteWSChannel : datosPaciente.IhusiClienteWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IhusiClienteWSClient : System.ServiceModel.ClientBase<datosPaciente.IhusiClienteWS>, datosPaciente.IhusiClienteWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IhusiClienteWSClient() : 
                base(IhusiClienteWSClient.GetDefaultBinding(), IhusiClienteWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IhusiClienteWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IhusiClienteWSClient(EndpointConfiguration endpointConfiguration) : 
                base(IhusiClienteWSClient.GetBindingForEndpoint(endpointConfiguration), IhusiClienteWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IhusiClienteWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IhusiClienteWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IhusiClienteWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IhusiClienteWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IhusiClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ConsultaAsync(string nroDoc, byte tipo)
        {
            return base.Channel.ConsultaAsync(nroDoc, tipo);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAsync(string Cliente)
        {
            return base.Channel.ActualizarAsync(Cliente);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(string Cliente)
        {
            return base.Channel.InsertarAsync(Cliente);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaExtAsync(string paciente, byte tipo)
        {
            return base.Channel.ConsultaExtAsync(paciente, tipo);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaPctesExtAsync()
        {
            return base.Channel.ConsultaPctesExtAsync();
        }
        
        public System.Threading.Tasks.Task<string> PacientesAsync(string nroDoc)
        {
            return base.Channel.PacientesAsync(nroDoc);
        }
        
        public System.Threading.Tasks.Task<datosPaciente.husiCliente> consPacienteAsync(string nroDoc, byte tipo)
        {
            return base.Channel.consPacienteAsync(nroDoc, tipo);
        }
        
        public System.Threading.Tasks.Task<string> Actualizar_V2Async(datosPaciente.husiCliente Cliente)
        {
            return base.Channel.Actualizar_V2Async(Cliente);
        }
        
        public System.Threading.Tasks.Task<string> Actualizar_V3Async(datosPaciente.husiCliente Cliente)
        {
            return base.Channel.Actualizar_V3Async(Cliente);
        }
        
        public System.Threading.Tasks.Task<string> Insertar_V2Async(datosPaciente.husiCliente Cliente)
        {
            return base.Channel.Insertar_V2Async(Cliente);
        }
        
        public System.Threading.Tasks.Task<string> Insertar_V3Async(datosPaciente.husiCliente Cliente)
        {
            return base.Channel.Insertar_V3Async(Cliente);
        }
        
        public System.Threading.Tasks.Task<datosPaciente.husiCliente> Consulta_V2Async(string nroDoc, byte tipo)
        {
            return base.Channel.Consulta_V2Async(nroDoc, tipo);
        }
        
        public System.Threading.Tasks.Task<short> segmentoPacienteAsync(int idPaciente)
        {
            return base.Channel.segmentoPacienteAsync(idPaciente);
        }
        
        public System.Threading.Tasks.Task<datosPaciente.habeasData> HBConsPacienteAsync(string nroDoc, short tipoDoc, System.DateTime fechaNacimiento)
        {
            return base.Channel.HBConsPacienteAsync(nroDoc, tipoDoc, fechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<datosPaciente.husiCliente> Consulta_V3Async(string idCliente)
        {
            return base.Channel.Consulta_V3Async(idCliente);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IhusiClienteWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IhusiClienteWS))
            {
                return new System.ServiceModel.EndpointAddress("http://winpvtiws01:8096/husiClienteWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IhusiClienteWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IhusiClienteWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IhusiClienteWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IhusiClienteWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IhusiClienteWS,
        }
    }
}
